data:
    type: "LLdataset"
    train_dataset: "unpaired"
    val_dataset: "LOLv1"
    patch_size: 512
    channels: 3
    num_workers: 6
    data_dir: "./data/Image_restoration/LOL-v1/"
    ckpt_dir: "ckpt/stage2"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000
    num_sampling_timesteps: 20

training:
    batch_size: 32
    n_epochs: 2500
    validation_freq: 10000

sampling:
    batch_size: 1

optim:
    beta1: 0.5
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001